# Generated by Django 5.2.12 on 2026-05-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinquiry',
            name='inquiry_tag',
            field=models.CharField(blank=True, choices=[('bulk_order', 'Bulk order'), ('delivery', 'Delivery'), ('complaint', 'Complaint'), ('general', 'General')], help_text='Auto-classified by AI on save.', max_length=20),
        ),
    ]
