# Generated by Django 5.2.13 on 2026-04-24 00:04

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_color_product_old_price_product_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sizes',
            field=models.CharField(blank=True, help_text='Comma-separated EU sizes, e.g. 32,34,36,38,40,42,44,46,48,50,52,54', max_length=200, validators=[inventory.models.validate_eu_sizes]),
        ),
    ]
