# Generated by Django 5.2.13 on 2026-05-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_sync_in_stock_with_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
