# Generated by Django 5.2.12 on 2026-05-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreview',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Auto-detected by AI when the review is approved.', max_length=10),
        ),
    ]
