# Generated by Django 5.2.13 on 2026-05-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPortalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Staff portal',
                'verbose_name_plural': 'Staff portal',
                'permissions': [('access_staff_dashboard', 'Can access staff dashboard')],
            },
        ),
    ]
